### ISSUE TITLE
demo is broken

### ISSUE THREAD

**Issue by milahu** [react-simple-code-editor/react-simple-code-editor#105]
http://satya164.xyz/react-simple-code-editor

> 404
>
> There isn't a GitHub Pages site here.

https://react-simple-code-editor.github.io/react-simple-code-editor/

&rarr; readme, not demo

**Comment by oliviertassinari** [comment]
@milahu I have updated 

<img width="323" alt="Screenshot 2022-11-15 at 23 28 24" src="https://user-images.githubusercontent.com/3165635/202038408-6072cb7f-e1e1-4cda-abf2-b9c35e7514f1.png">

Do you want to open a PR to fix? 

https://github.com/react-simple-code-editor/react-simple-code-editor/blob/4065fa6da6b7ca5eefc660b151fe5ab8b1a740cf/README.md?plain=1#L87

**Comment by senali-d** [comment]
Can I open a PR to fix this issue
