### ISSUE TITLE
Doesn't it support multiple languages?

### ISSUE THREAD

**Issue by RQsky** [react-simple-code-editor/react-simple-code-editor#115]
Doesn't it support multiple languages?

**Comment by safdaraliniazi** [comment]
it support using prismjs

**Comment by alihammad99** [comment]
✅ `import { highlight, languages } from "prismjs";`
❌ `import { highlight, languages } from "prismjs/components/prism-core";`

✅ ```
<Editor
    ....
    highlight={(code) => highlight(code, languages.css, "css")}
```
