### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jahewson** [react-simple-code-editor/react-simple-code-editor#31]
I see various references to the MIT License, but the license itself is missing.

**Comment by 3pns** [comment]
I want to use this component as well but can't due to lack of MIT Licence, it would be great if the author decide to license it.

**Comment by chris-armstrong** [comment]
There's a reference in the package.json, so it should just be a matter of submitting a PR with the MIT boilerplate in a top-level LICENSE.md file.

**Comment by oliviertassinari** [comment]
The license is available in the archive https://unpkg.com/browse/react-simple-code-editor@0.13.1/LICENSE.md and the repository https://github.com/react-simple-code-editor/react-simple-code-editor/blob/29a9740e6e3b90713c6ca37e2a99b64764557a10/LICENSE.md?plain=1#L1

https://github.com/react-simple-code-editor/react-simple-code-editor/blob/29a9740e6e3b90713c6ca37e2a99b64764557a10/package.json#L33
