### ISSUE TITLE
readonly

### ISSUE THREAD

**Issue by DevMammadov** [react-simple-code-editor/react-simple-code-editor#90]
### Current behaviour

only editable

### Expected behaviour

i want to make it readonly untill user click to edit button with `readonly={true || false}` method

### Code sample

` <Editor
       readonly={true}
/>`

**Comment by rivaslive** [comment]
If you examine the code you will notice that you can pass readOnly or disabled as booleans.
Pass readOnly and not readonly

**Comment by rivaslive** [comment]
It's a shame that the creator of this package no longer supports it.
